version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diary-web
    ports:
      - "5001:5000"
    env_file:
      - .env
    restart: always
    networks:
      - diary_net

networks:
  diary_net:
    external: true

