version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diary-web-v2
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  registry:
    image: registry:2
    container_name: registry-v2
    ports:
      - "5000:5000"
    restart: always

volumes:
  db_data:
